apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: ca-issuer
spec:
  ca:
    secretName: ca-secret
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: fcm-cert
spec:
  secretName: fcm-tls
  issuerRef:
    name: ca-issuer
    kind: ClusterIssuer
  commonName: fcm-service
  duration: 3650h
  usages:
    - server auth
    - client auth
